name: ChenYFanのHexoBlogBuild
'on':
  - workflow_dispatch
  - push
jobs:
  buildstatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install & Build
        run: >
          npm install -g hexo-cli

          npm i

          # Restore last modified time

          git ls-files -z | while read -d '' path; do touch -d "$(git log -1
          --format="@%ct" "$path")" "$path"; done

          hexo g

          curl -H 'Content-Type:text/plain' --data-binary
          @./public/baidu_urls.txt
          "http://data.zz.baidu.com/urls?site=https://blog.cyfan.top&token=${{
          secrets.BD_TOKEN }}"

          rm -rf ./public/CNAME

          echo "blog.cyfan.top" >> ./public/CNAME

          npm version patch --no-git-tag-version
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./public
          
